### ISSUE TITLE
Not all emojis are supported?

### ISSUE THREAD

**Issue by jeremy886** [lord63/pyemojify#3]
text = emojify("It's really great to see :smile: geeks :nerd: also have a sense of humor. Don't forget to see :penguin:  in Melbourne.")

print(text)

> > > text = emojify("It's really great to see :smile: geeks :nerd-like: also have a sense of humor. Don't forget to see :penguin: in Melbourne.") 
> > > print(text)
> > > It's really great to see 😄 geeks :nerd-like: also have a sense of humor. Don't forget to see 🐧 in Melbourne.

It's really great to see 😄 geeks :nerd: also have a sense of humor. Don't forget to see 🐧  in Melbourne.

**Comment by lord63** [comment]
Yes, it doesn't support all the emojis. In you example, github also can't recognize the :nerd: or :nerd-like: emoji.
